#############################################################################
# Makefile for building: libGardenOfEdenCreationKit.a
# Generated by qmake (2.01a) (Qt 5.0.0) on: ?? ????. 24 16:35:37 2012
# Project:  GardenOfEdenCreationKit.pro
# Template: lib
# Command: /usr/bin/qmake-qt5 -o Makefile GardenOfEdenCreationKit.pro
#############################################################################

####### Compiler, tools and options

CC            = @echo compiling $< && gcc
CXX           = @echo compiling $< && g++
DEFINES       = -DQWT_DLL -DQWT_NO_SVG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -fPIC -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Wextra -pedantic -Wold-style-cast -Winit-self -O2 -g -fPIC -Wall -W -std=c++0x -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt5/mkspecs/linux-g++ -I. -I../../tmp -I. -I/usr/lib/qwt-qt5/include -I/usr/lib/qt5/include -I/usr/lib/qt5/include/QtWidgets -I/usr/lib/qt5/include/QtGui -I/usr/lib/qt5/include/QtCore -I../../tmp
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt5
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ../../tmp/

####### Files

SOURCES       = ConnectionHolder.cpp \
		LedIndicator.cpp \
		Waiter.cpp ../../tmp/qrc_GardenOfEdenCreationKit.cpp \
		../../tmp/moc_Waiter.cpp
OBJECTS       = ../../tmp/ConnectionHolder.o \
		../../tmp/LedIndicator.o \
		../../tmp/Waiter.o \
		../../tmp/qrc_GardenOfEdenCreationKit.o \
		../../tmp/moc_Waiter.o
DIST          = /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_platformsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_serialport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_xml.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/unix/default_pre.prf \
		../../SelfWriter.pri \
		/usr/lib/qt5/mkspecs/features/debug.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/static.prf \
		/usr/lib/qt5/mkspecs/features/staticlib.prf \
		/usr/lib/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/c++11.prf \
		/usr/lib/qt5/mkspecs/features/silent.prf \
		/usr/lib/qwt-qt5/features/qwtconfig.pri \
		/usr/lib/qwt-qt5/features/qwtfunctions.pri \
		/usr/lib/qwt-qt5/features/qwt.prf \
		/usr/lib/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/wayland-scanner.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		GardenOfEdenCreationKit.qrc \
		GardenOfEdenCreationKit.pro
QMAKE_TARGET  = GardenOfEdenCreationKit
DESTDIR       = ../../build/
TARGET        = libGardenOfEdenCreationKit.a


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile ../../build/libGardenOfEdenCreationKit.prl ../../build/GardenOfEdenCreationKit.pc ../../build/$(TARGET) 

staticlib: ../../build/$(TARGET)

../../build/$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	@test -d ../../build/ || $(MKDIR) ../../build/ 
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)
	cp -f ConnectionHolder.h /home/ndtimofeev/Проекты/SelfWriter/build 
	 cp -f LedIndicator.h /home/ndtimofeev/Проекты/SelfWriter/build 
	 cp -f SetExt.h /home/ndtimofeev/Проекты/SelfWriter/build 
	 cp -f SmartPointers.h /home/ndtimofeev/Проекты/SelfWriter/build 
	 cp -f Waiter.h /home/ndtimofeev/Проекты/SelfWriter/build 
	 cp -f MapExt.h /home/ndtimofeev/Проекты/SelfWriter/build 
	 cp -f UniqueObjectHolder.h /home/ndtimofeev/Проекты/SelfWriter/build 
	 cp -f TypeTricks.h /home/ndtimofeev/Проекты/SelfWriter/build 
	 cp -f VariantExt.h /home/ndtimofeev/Проекты/SelfWriter/build 
	
	-$(DEL_FILE) ../../build/$(TARGET)
	-$(MOVE) $(TARGET) ../../build/


../../build/libGardenOfEdenCreationKit.prl: 
	@$(QMAKE) -prl  GardenOfEdenCreationKit.pro
Makefile: GardenOfEdenCreationKit.pro /usr/lib/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_platformsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_serialport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_xml.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/unix/default_pre.prf \
		../../SelfWriter.pri \
		/usr/lib/qt5/mkspecs/features/debug.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/static.prf \
		/usr/lib/qt5/mkspecs/features/staticlib.prf \
		/usr/lib/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/c++11.prf \
		/usr/lib/qt5/mkspecs/features/silent.prf \
		/usr/lib/qwt-qt5/features/qwtconfig.pri \
		/usr/lib/qwt-qt5/features/qwtfunctions.pri \
		/usr/lib/qwt-qt5/features/qwt.prf \
		/usr/lib/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/wayland-scanner.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		GardenOfEdenCreationKit.qrc \
		/usr/lib/qt5/lib/libQtWidgets.prl \
		/usr/lib/qt5/lib/libQtGui.prl \
		/usr/lib/qt5/lib/libQtCore.prl
	$(QMAKE) -o Makefile GardenOfEdenCreationKit.pro
/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/qt5/mkspecs/common/unix.conf:
/usr/lib/qt5/mkspecs/common/linux.conf:
/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt5/mkspecs/common/g++-base.conf:
/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/qt5/mkspecs/qconfig.pri:
/usr/lib/qt5/mkspecs/modules/qt_concurrent.pri:
/usr/lib/qt5/mkspecs/modules/qt_core.pri:
/usr/lib/qt5/mkspecs/modules/qt_dbus.pri:
/usr/lib/qt5/mkspecs/modules/qt_gui.pri:
/usr/lib/qt5/mkspecs/modules/qt_network.pri:
/usr/lib/qt5/mkspecs/modules/qt_opengl.pri:
/usr/lib/qt5/mkspecs/modules/qt_platformsupport.pri:
/usr/lib/qt5/mkspecs/modules/qt_printsupport.pri:
/usr/lib/qt5/mkspecs/modules/qt_serialport.pri:
/usr/lib/qt5/mkspecs/modules/qt_sql.pri:
/usr/lib/qt5/mkspecs/modules/qt_testlib.pri:
/usr/lib/qt5/mkspecs/modules/qt_widgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_xml.pri:
/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/qt5/mkspecs/features/qt_config.prf:
/usr/lib/qt5/mkspecs/features/spec_post.prf:
/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt5/mkspecs/features/default_pre.prf:
/usr/lib/qt5/mkspecs/features/unix/default_pre.prf:
../../SelfWriter.pri:
/usr/lib/qt5/mkspecs/features/debug.prf:
/usr/lib/qt5/mkspecs/features/default_post.prf:
/usr/lib/qt5/mkspecs/features/static.prf:
/usr/lib/qt5/mkspecs/features/staticlib.prf:
/usr/lib/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/qt5/mkspecs/features/warn_on.prf:
/usr/lib/qt5/mkspecs/features/c++11.prf:
/usr/lib/qt5/mkspecs/features/silent.prf:
/usr/lib/qwt-qt5/features/qwtconfig.pri:
/usr/lib/qwt-qt5/features/qwtfunctions.pri:
/usr/lib/qwt-qt5/features/qwt.prf:
/usr/lib/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/qt5/mkspecs/features/qt.prf:
/usr/lib/qt5/mkspecs/features/resources.prf:
/usr/lib/qt5/mkspecs/features/moc.prf:
/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/qt5/mkspecs/features/uic.prf:
/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/qt5/mkspecs/features/wayland-scanner.prf:
/usr/lib/qt5/mkspecs/features/exceptions.prf:
/usr/lib/qt5/mkspecs/features/yacc.prf:
/usr/lib/qt5/mkspecs/features/lex.prf:
GardenOfEdenCreationKit.qrc:
/usr/lib/qt5/lib/libQtWidgets.prl:
/usr/lib/qt5/lib/libQtGui.prl:
/usr/lib/qt5/lib/libQtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile GardenOfEdenCreationKit.pro

qmake_all: FORCE

../../build/GardenOfEdenCreationKit.pc: 
	@$(QMAKE) -prl  /home/ndtimofeev/Проекты/SelfWriter/src/GardenOfEdenCreationKit/GardenOfEdenCreationKit.pro
dist: 
	@test -d ../../tmp/GardenOfEdenCreationKit1.0.0 || $(MKDIR) ../../tmp/GardenOfEdenCreationKit1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) ../../tmp/GardenOfEdenCreationKit1.0.0/ && $(COPY_FILE) --parents GardenOfEdenCreationKit.qrc ../../tmp/GardenOfEdenCreationKit1.0.0/ && $(COPY_FILE) --parents ConnectionHolder.h LedIndicator.h SetExt.h SmartPointers.h Waiter.h MapExt.h UniqueObjectHolder.h TypeTricks.h VariantExt.h ../../tmp/GardenOfEdenCreationKit1.0.0/ && $(COPY_FILE) --parents ConnectionHolder.cpp LedIndicator.cpp Waiter.cpp ../../tmp/GardenOfEdenCreationKit1.0.0/ && (cd `dirname ../../tmp/GardenOfEdenCreationKit1.0.0` && $(TAR) GardenOfEdenCreationKit1.0.0.tar GardenOfEdenCreationKit1.0.0 && $(COMPRESS) GardenOfEdenCreationKit1.0.0.tar) && $(MOVE) `dirname ../../tmp/GardenOfEdenCreationKit1.0.0`/GardenOfEdenCreationKit1.0.0.tar.gz . && $(DEL_FILE) -r ../../tmp/GardenOfEdenCreationKit1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

docs:

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_rcc_make_all: ../../tmp/qrc_GardenOfEdenCreationKit.cpp
compiler_rcc_clean:
	-$(DEL_FILE) ../../tmp/qrc_GardenOfEdenCreationKit.cpp
../../tmp/qrc_GardenOfEdenCreationKit.cpp: GardenOfEdenCreationKit.qrc \
		images/greenLedOff.png \
		images/greenLedOn.png \
		images/redLedOn.png
	@echo rcc GardenOfEdenCreationKit.qrc && /usr/lib/qt5/bin/rcc -name GardenOfEdenCreationKit GardenOfEdenCreationKit.qrc -o ../../tmp/qrc_GardenOfEdenCreationKit.cpp

compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_moc_header_make_all: ../../tmp/moc_Waiter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) ../../tmp/moc_Waiter.cpp
../../tmp/moc_Waiter.cpp: ConnectionHolder.h \
		Waiter.h
	@echo moc Waiter.h && /usr/lib/qt5/bin/moc $(DEFINES) $(INCPATH) Waiter.h -o ../../tmp/moc_Waiter.cpp

compiler_image_collection_make_all: ../../tmp/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ../../tmp/qmake_image_collection.cpp
compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

../../tmp/ConnectionHolder.o: ConnectionHolder.cpp ConnectionHolder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/ConnectionHolder.o ConnectionHolder.cpp

../../tmp/LedIndicator.o: LedIndicator.cpp LedIndicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/LedIndicator.o LedIndicator.cpp

../../tmp/Waiter.o: Waiter.cpp ConnectionHolder.h \
		Waiter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/Waiter.o Waiter.cpp

../../tmp/qrc_GardenOfEdenCreationKit.o: ../../tmp/qrc_GardenOfEdenCreationKit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/qrc_GardenOfEdenCreationKit.o ../../tmp/qrc_GardenOfEdenCreationKit.cpp

../../tmp/moc_Waiter.o: ../../tmp/moc_Waiter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/moc_Waiter.o ../../tmp/moc_Waiter.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

