#############################################################################
# Makefile for building: libGardenOfEdenCreationKit.a
# Generated by qmake (3.0) (Qt 5.0.0) on: ?? ????? 16 20:09:45 2013
# Project:  GardenOfEdenCreationKit.pro
# Template: lib
# Command: /usr/bin/qmake-qt5 -o Makefile GardenOfEdenCreationKit.pro
#############################################################################

####### Compiler, tools and options

CC            = @echo compiling $< && gcc
CXX           = @echo compiling $< && g++
DEFINES       = -DQWT_DLL -DQWT_NO_SVG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -fPIC -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Wextra -pedantic -Wold-style-cast -Winit-self -O2 -g -fPIC -Wall -W -std=c++0x -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt5/mkspecs/linux-g++ -I. -I../../tmp -I. -I/usr/lib/qwt-qt5/include -I/usr/lib/qt5/include -I/usr/lib/qt5/include/QtWidgets -I/usr/lib/qt5/include/QtGui -I/usr/lib/qt5/include/QtCore -I../../tmp
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt5
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ../../tmp/

####### Files

SOURCES       = ConnectionHolder.cpp \
		CustomizableItemDelegate.cpp \
		CustomizableSpinBox.cpp \
		CustomizableState.cpp \
		LedIndicator.cpp \
		ScopedPropertyRollback.cpp \
		Validator.cpp \
		Waiter.cpp ../../tmp/qrc_GardenOfEdenCreationKit.cpp \
		../../tmp/moc_CustomizableState.cpp \
		../../tmp/moc_Waiter.cpp
OBJECTS       = ../../tmp/ConnectionHolder.o \
		../../tmp/CustomizableItemDelegate.o \
		../../tmp/CustomizableSpinBox.o \
		../../tmp/CustomizableState.o \
		../../tmp/LedIndicator.o \
		../../tmp/ScopedPropertyRollback.o \
		../../tmp/Validator.o \
		../../tmp/Waiter.o \
		../../tmp/qrc_GardenOfEdenCreationKit.o \
		../../tmp/moc_CustomizableState.o \
		../../tmp/moc_Waiter.o
DIST          = /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/unix/default_pre.prf \
		../../SelfWriter.pri \
		/usr/lib/qt5/mkspecs/features/debug.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/static.prf \
		/usr/lib/qt5/mkspecs/features/staticlib.prf \
		/usr/lib/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/c++11.prf \
		/usr/lib/qt5/mkspecs/features/silent.prf \
		/usr/lib/qwt-qt5/features/qwtconfig.pri \
		/usr/lib/qwt-qt5/features/qwtfunctions.pri \
		/usr/lib/qwt-qt5/features/qwt.prf \
		/usr/lib/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/wayland-scanner.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		GardenOfEdenCreationKit.pro \
		GardenOfEdenCreationKit.qrc \
		GardenOfEdenCreationKit.pro
QMAKE_TARGET  = GardenOfEdenCreationKit
DESTDIR       = ../../build/
TARGET        = libGardenOfEdenCreationKit.a


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile ../../build/libGardenOfEdenCreationKit.prl ../../build/GardenOfEdenCreationKit.pc ../../build/$(TARGET) 

staticlib: ../../build/$(TARGET)

../../build/$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	@test -d ../../build/ || $(MKDIR) ../../build/ 
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)
	cp -f Bits.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f ConnectionHolder.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f CustomizableItemDelegate.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f CustomizableSignalTransition.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f CustomizableSpinBox.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f CustomizableState.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f LedIndicator.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f MapExt.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f ScopedPropertyRollback.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f SetExt.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f SignalTransition.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f SmartPointers.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f TypeTricks.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f UniqueList.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f UniqueObjectHolder.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f Validator.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f VariantExt.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	 cp -f Waiter.h /home/ndtimofeev/Проекты/SelfWriter/SelfWriter/build 
	
	-$(DEL_FILE) ../../build/$(TARGET)
	-$(MOVE) $(TARGET) ../../build/


../../build/libGardenOfEdenCreationKit.prl: 
	@$(QMAKE) -prl  GardenOfEdenCreationKit.pro
Makefile: GardenOfEdenCreationKit.pro /usr/lib/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_3d.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/unix/default_pre.prf \
		../../SelfWriter.pri \
		/usr/lib/qt5/mkspecs/features/debug.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/static.prf \
		/usr/lib/qt5/mkspecs/features/staticlib.prf \
		/usr/lib/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/c++11.prf \
		/usr/lib/qt5/mkspecs/features/silent.prf \
		/usr/lib/qwt-qt5/features/qwtconfig.pri \
		/usr/lib/qwt-qt5/features/qwtfunctions.pri \
		/usr/lib/qwt-qt5/features/qwt.prf \
		/usr/lib/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/wayland-scanner.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		GardenOfEdenCreationKit.pro \
		GardenOfEdenCreationKit.qrc \
		/usr/lib/qt5/lib/libQtWidgets.prl \
		/usr/lib/qt5/lib/libQtGui.prl \
		/usr/lib/qt5/lib/libQtCore.prl
	$(QMAKE) -o Makefile GardenOfEdenCreationKit.pro
/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/qt5/mkspecs/common/unix.conf:
/usr/lib/qt5/mkspecs/common/linux.conf:
/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt5/mkspecs/common/g++-base.conf:
/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/qt5/mkspecs/qconfig.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_3d.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_platformsupport.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/qt5/mkspecs/features/qt_config.prf:
/usr/lib/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt5/mkspecs/features/spec_post.prf:
/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt5/mkspecs/features/default_pre.prf:
/usr/lib/qt5/mkspecs/features/unix/default_pre.prf:
../../SelfWriter.pri:
/usr/lib/qt5/mkspecs/features/debug.prf:
/usr/lib/qt5/mkspecs/features/default_post.prf:
/usr/lib/qt5/mkspecs/features/static.prf:
/usr/lib/qt5/mkspecs/features/staticlib.prf:
/usr/lib/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/qt5/mkspecs/features/warn_on.prf:
/usr/lib/qt5/mkspecs/features/c++11.prf:
/usr/lib/qt5/mkspecs/features/silent.prf:
/usr/lib/qwt-qt5/features/qwtconfig.pri:
/usr/lib/qwt-qt5/features/qwtfunctions.pri:
/usr/lib/qwt-qt5/features/qwt.prf:
/usr/lib/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/qt5/mkspecs/features/qt.prf:
/usr/lib/qt5/mkspecs/features/resources.prf:
/usr/lib/qt5/mkspecs/features/moc.prf:
/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/qt5/mkspecs/features/uic.prf:
/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/qt5/mkspecs/features/wayland-scanner.prf:
/usr/lib/qt5/mkspecs/features/exceptions.prf:
/usr/lib/qt5/mkspecs/features/yacc.prf:
/usr/lib/qt5/mkspecs/features/lex.prf:
GardenOfEdenCreationKit.pro:
GardenOfEdenCreationKit.qrc:
/usr/lib/qt5/lib/libQtWidgets.prl:
/usr/lib/qt5/lib/libQtGui.prl:
/usr/lib/qt5/lib/libQtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile GardenOfEdenCreationKit.pro

qmake_all: FORCE

../../build/GardenOfEdenCreationKit.pc: 
	@$(QMAKE) -prl  GardenOfEdenCreationKit.pro
dist: 
	@test -d ../../tmp/GardenOfEdenCreationKit1.0.0 || $(MKDIR) ../../tmp/GardenOfEdenCreationKit1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) ../../tmp/GardenOfEdenCreationKit1.0.0/ && $(COPY_FILE) --parents GardenOfEdenCreationKit.qrc ../../tmp/GardenOfEdenCreationKit1.0.0/ && $(COPY_FILE) --parents Bits.h ConnectionHolder.h CustomizableItemDelegate.h CustomizableSignalTransition.h CustomizableSpinBox.h CustomizableState.h LedIndicator.h MapExt.h ScopedPropertyRollback.h SetExt.h SignalTransition.h SmartPointers.h TypeTricks.h UniqueList.h UniqueObjectHolder.h Validator.h VariantExt.h Waiter.h ../../tmp/GardenOfEdenCreationKit1.0.0/ && $(COPY_FILE) --parents ConnectionHolder.cpp CustomizableItemDelegate.cpp CustomizableSpinBox.cpp CustomizableState.cpp LedIndicator.cpp ScopedPropertyRollback.cpp Validator.cpp Waiter.cpp ../../tmp/GardenOfEdenCreationKit1.0.0/ && (cd `dirname ../../tmp/GardenOfEdenCreationKit1.0.0` && $(TAR) GardenOfEdenCreationKit1.0.0.tar GardenOfEdenCreationKit1.0.0 && $(COMPRESS) GardenOfEdenCreationKit1.0.0.tar) && $(MOVE) `dirname ../../tmp/GardenOfEdenCreationKit1.0.0`/GardenOfEdenCreationKit1.0.0.tar.gz . && $(DEL_FILE) -r ../../tmp/GardenOfEdenCreationKit1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

docs:

install_docs:

uninstall_docs:

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_rcc_make_all: ../../tmp/qrc_GardenOfEdenCreationKit.cpp
compiler_rcc_clean:
	-$(DEL_FILE) ../../tmp/qrc_GardenOfEdenCreationKit.cpp
../../tmp/qrc_GardenOfEdenCreationKit.cpp: GardenOfEdenCreationKit.qrc \
		images/redLedOn.png \
		images/greenLedOff.png \
		images/greenLedOn.png
	@echo rcc GardenOfEdenCreationKit.qrc && /usr/lib/qt5/bin/rcc -name GardenOfEdenCreationKit GardenOfEdenCreationKit.qrc -o ../../tmp/qrc_GardenOfEdenCreationKit.cpp

compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_moc_header_make_all: ../../tmp/moc_CustomizableState.cpp ../../tmp/moc_Waiter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) ../../tmp/moc_CustomizableState.cpp ../../tmp/moc_Waiter.cpp
../../tmp/moc_CustomizableState.cpp: /usr/lib/qt5/include/QtCore/QObject \
		/usr/lib/qt5/include/QtCore/qobject.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib/qt5/include/QtCore/qnamespace.h \
		/usr/lib/qt5/include/QtCore/qglobal.h \
		/usr/lib/qt5/include/QtCore/qconfig.h \
		/usr/lib/qt5/include/QtCore/qfeatures.h \
		/usr/lib/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib/qt5/include/QtCore/qlogging.h \
		/usr/lib/qt5/include/QtCore/qflags.h \
		/usr/lib/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib/qt5/include/QtCore/qtypetraits.h \
		/usr/lib/qt5/include/QtCore/qsysinfo.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib/qt5/include/QtCore/qstring.h \
		/usr/lib/qt5/include/QtCore/qchar.h \
		/usr/lib/qt5/include/QtCore/qbytearray.h \
		/usr/lib/qt5/include/QtCore/qrefcount.h \
		/usr/lib/qt5/include/QtCore/qatomic.h \
		/usr/lib/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib/qt5/include/QtCore/qatomic_power.h \
		/usr/lib/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib/qt5/include/QtCore/qarraydata.h \
		/usr/lib/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib/qt5/include/QtCore/qlist.h \
		/usr/lib/qt5/include/QtCore/qalgorithms.h \
		/usr/lib/qt5/include/QtCore/qiterator.h \
		/usr/lib/qt5/include/QtCore/qcoreevent.h \
		/usr/lib/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib/qt5/include/QtCore/qmetatype.h \
		/usr/lib/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib/qt5/include/QtCore/qisenum.h \
		/usr/lib/qt5/include/QtCore/qobject_impl.h \
		/usr/lib/qt5/include/QtCore/QState \
		/usr/lib/qt5/include/QtCore/qstate.h \
		/usr/lib/qt5/include/QtCore/qabstractstate.h \
		/usr/lib/qt5/include/QtCore/QEvent \
		/usr/lib/qt5/include/QtCore/QAbstractState \
		/usr/lib/qt5/include/QtCore/QVector \
		/usr/lib/qt5/include/QtCore/qvector.h \
		/usr/lib/qt5/include/QtCore/qpoint.h \
		/usr/lib/qt5/include/QtCore/QLatin1String \
		/usr/lib/qt5/include/QtCore/QVariant \
		/usr/lib/qt5/include/QtCore/qvariant.h \
		/usr/lib/qt5/include/QtCore/qmap.h \
		/usr/lib/qt5/include/QtCore/qpair.h \
		/usr/lib/qt5/include/QtCore/qdebug.h \
		/usr/lib/qt5/include/QtCore/qhash.h \
		/usr/lib/qt5/include/QtCore/qtextstream.h \
		/usr/lib/qt5/include/QtCore/qiodevice.h \
		/usr/lib/qt5/include/QtCore/qlocale.h \
		/usr/lib/qt5/include/QtCore/qshareddata.h \
		/usr/lib/qt5/include/QtCore/qset.h \
		/usr/lib/qt5/include/QtCore/qcontiguouscache.h \
		CustomizableState.h
	@echo moc CustomizableState.h && /usr/lib/qt5/bin/moc $(DEFINES) $(INCPATH) CustomizableState.h -o ../../tmp/moc_CustomizableState.cpp

../../tmp/moc_Waiter.cpp: /usr/lib/qt5/include/QtCore/QCoreApplication \
		/usr/lib/qt5/include/QtCore/qcoreapplication.h \
		/usr/lib/qt5/include/QtCore/qobject.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib/qt5/include/QtCore/qnamespace.h \
		/usr/lib/qt5/include/QtCore/qglobal.h \
		/usr/lib/qt5/include/QtCore/qconfig.h \
		/usr/lib/qt5/include/QtCore/qfeatures.h \
		/usr/lib/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib/qt5/include/QtCore/qlogging.h \
		/usr/lib/qt5/include/QtCore/qflags.h \
		/usr/lib/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib/qt5/include/QtCore/qtypetraits.h \
		/usr/lib/qt5/include/QtCore/qsysinfo.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib/qt5/include/QtCore/qstring.h \
		/usr/lib/qt5/include/QtCore/qchar.h \
		/usr/lib/qt5/include/QtCore/qbytearray.h \
		/usr/lib/qt5/include/QtCore/qrefcount.h \
		/usr/lib/qt5/include/QtCore/qatomic.h \
		/usr/lib/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib/qt5/include/QtCore/qatomic_power.h \
		/usr/lib/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib/qt5/include/QtCore/qarraydata.h \
		/usr/lib/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib/qt5/include/QtCore/qlist.h \
		/usr/lib/qt5/include/QtCore/qalgorithms.h \
		/usr/lib/qt5/include/QtCore/qiterator.h \
		/usr/lib/qt5/include/QtCore/qcoreevent.h \
		/usr/lib/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib/qt5/include/QtCore/qmetatype.h \
		/usr/lib/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib/qt5/include/QtCore/qisenum.h \
		/usr/lib/qt5/include/QtCore/qobject_impl.h \
		/usr/lib/qt5/include/QtCore/qeventloop.h \
		/usr/lib/qt5/include/QtCore/QElapsedTimer \
		/usr/lib/qt5/include/QtCore/qelapsedtimer.h \
		/usr/lib/qt5/include/QtCore/QList \
		/usr/lib/qt5/include/QtCore/QMetaObject \
		/usr/lib/qt5/include/QtCore/QObject \
		/usr/lib/qt5/include/QtCore/QVariant \
		/usr/lib/qt5/include/QtCore/qvariant.h \
		/usr/lib/qt5/include/QtCore/qmap.h \
		/usr/lib/qt5/include/QtCore/qpair.h \
		/usr/lib/qt5/include/QtCore/qdebug.h \
		/usr/lib/qt5/include/QtCore/qhash.h \
		/usr/lib/qt5/include/QtCore/qtextstream.h \
		/usr/lib/qt5/include/QtCore/qiodevice.h \
		/usr/lib/qt5/include/QtCore/qlocale.h \
		/usr/lib/qt5/include/QtCore/qshareddata.h \
		/usr/lib/qt5/include/QtCore/qvector.h \
		/usr/lib/qt5/include/QtCore/qpoint.h \
		/usr/lib/qt5/include/QtCore/qset.h \
		/usr/lib/qt5/include/QtCore/qcontiguouscache.h \
		ConnectionHolder.h \
		/usr/lib/qt5/include/QtCore/QVector \
		Waiter.h
	@echo moc Waiter.h && /usr/lib/qt5/bin/moc $(DEFINES) $(INCPATH) Waiter.h -o ../../tmp/moc_Waiter.cpp

compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

../../tmp/ConnectionHolder.o: ConnectionHolder.cpp /usr/lib/qt5/include/QtCore/QList \
		/usr/lib/qt5/include/QtCore/qlist.h \
		/usr/lib/qt5/include/QtCore/qalgorithms.h \
		/usr/lib/qt5/include/QtCore/qglobal.h \
		/usr/lib/qt5/include/QtCore/qconfig.h \
		/usr/lib/qt5/include/QtCore/qfeatures.h \
		/usr/lib/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib/qt5/include/QtCore/qlogging.h \
		/usr/lib/qt5/include/QtCore/qflags.h \
		/usr/lib/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib/qt5/include/QtCore/qtypetraits.h \
		/usr/lib/qt5/include/QtCore/qsysinfo.h \
		/usr/lib/qt5/include/QtCore/qiterator.h \
		/usr/lib/qt5/include/QtCore/qrefcount.h \
		/usr/lib/qt5/include/QtCore/qatomic.h \
		/usr/lib/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib/qt5/include/QtCore/qatomic_power.h \
		/usr/lib/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib/qt5/include/QtCore/QMetaObject \
		/usr/lib/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib/qt5/include/QtCore/qnamespace.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib/qt5/include/QtCore/QObject \
		/usr/lib/qt5/include/QtCore/qobject.h \
		/usr/lib/qt5/include/QtCore/qstring.h \
		/usr/lib/qt5/include/QtCore/qchar.h \
		/usr/lib/qt5/include/QtCore/qbytearray.h \
		/usr/lib/qt5/include/QtCore/qarraydata.h \
		/usr/lib/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib/qt5/include/QtCore/qcoreevent.h \
		/usr/lib/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib/qt5/include/QtCore/qmetatype.h \
		/usr/lib/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib/qt5/include/QtCore/qisenum.h \
		/usr/lib/qt5/include/QtCore/qobject_impl.h \
		/usr/lib/qt5/include/QtCore/QDebug \
		/usr/lib/qt5/include/QtCore/qdebug.h \
		/usr/lib/qt5/include/QtCore/qhash.h \
		/usr/lib/qt5/include/QtCore/qpair.h \
		/usr/lib/qt5/include/QtCore/qmap.h \
		/usr/lib/qt5/include/QtCore/qtextstream.h \
		/usr/lib/qt5/include/QtCore/qiodevice.h \
		/usr/lib/qt5/include/QtCore/qlocale.h \
		/usr/lib/qt5/include/QtCore/qvariant.h \
		/usr/lib/qt5/include/QtCore/qshareddata.h \
		/usr/lib/qt5/include/QtCore/qvector.h \
		/usr/lib/qt5/include/QtCore/qpoint.h \
		/usr/lib/qt5/include/QtCore/qset.h \
		/usr/lib/qt5/include/QtCore/qcontiguouscache.h \
		ConnectionHolder.h \
		/usr/lib/qt5/include/QtCore/QVector
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/ConnectionHolder.o ConnectionHolder.cpp

../../tmp/CustomizableItemDelegate.o: CustomizableItemDelegate.cpp CustomizableItemDelegate.h \
		/usr/lib/qt5/include/QtCore/QAbstractItemModel \
		/usr/lib/qt5/include/QtCore/qabstractitemmodel.h \
		/usr/lib/qt5/include/QtCore/qvariant.h \
		/usr/lib/qt5/include/QtCore/qatomic.h \
		/usr/lib/qt5/include/QtCore/qglobal.h \
		/usr/lib/qt5/include/QtCore/qconfig.h \
		/usr/lib/qt5/include/QtCore/qfeatures.h \
		/usr/lib/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib/qt5/include/QtCore/qlogging.h \
		/usr/lib/qt5/include/QtCore/qflags.h \
		/usr/lib/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib/qt5/include/QtCore/qtypetraits.h \
		/usr/lib/qt5/include/QtCore/qsysinfo.h \
		/usr/lib/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib/qt5/include/QtCore/qatomic_power.h \
		/usr/lib/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib/qt5/include/QtCore/qbytearray.h \
		/usr/lib/qt5/include/QtCore/qrefcount.h \
		/usr/lib/qt5/include/QtCore/qnamespace.h \
		/usr/lib/qt5/include/QtCore/qarraydata.h \
		/usr/lib/qt5/include/QtCore/qstring.h \
		/usr/lib/qt5/include/QtCore/qchar.h \
		/usr/lib/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib/qt5/include/QtCore/qlist.h \
		/usr/lib/qt5/include/QtCore/qalgorithms.h \
		/usr/lib/qt5/include/QtCore/qiterator.h \
		/usr/lib/qt5/include/QtCore/qmetatype.h \
		/usr/lib/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib/qt5/include/QtCore/qisenum.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib/qt5/include/QtCore/qmap.h \
		/usr/lib/qt5/include/QtCore/qpair.h \
		/usr/lib/qt5/include/QtCore/qdebug.h \
		/usr/lib/qt5/include/QtCore/qhash.h \
		/usr/lib/qt5/include/QtCore/qtextstream.h \
		/usr/lib/qt5/include/QtCore/qiodevice.h \
		/usr/lib/qt5/include/QtCore/qobject.h \
		/usr/lib/qt5/include/QtCore/qcoreevent.h \
		/usr/lib/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib/qt5/include/QtCore/qobject_impl.h \
		/usr/lib/qt5/include/QtCore/qlocale.h \
		/usr/lib/qt5/include/QtCore/qshareddata.h \
		/usr/lib/qt5/include/QtCore/qvector.h \
		/usr/lib/qt5/include/QtCore/qpoint.h \
		/usr/lib/qt5/include/QtCore/qset.h \
		/usr/lib/qt5/include/QtCore/qcontiguouscache.h \
		/usr/lib/qt5/include/QtCore/QLocale \
		/usr/lib/qt5/include/QtCore/QModelIndex \
		/usr/lib/qt5/include/QtCore/QObject \
		/usr/lib/qt5/include/QtCore/QString \
		/usr/lib/qt5/include/QtCore/QVariant \
		/usr/lib/qt5/include/QtWidgets/QStyleOptionViewItem \
		/usr/lib/qt5/include/QtWidgets/qstyleoption.h \
		/usr/lib/qt5/include/QtWidgets/qabstractspinbox.h \
		/usr/lib/qt5/include/QtWidgets/qwidget.h \
		/usr/lib/qt5/include/QtGui/qwindowdefs.h \
		/usr/lib/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/lib/qt5/include/QtCore/qmargins.h \
		/usr/lib/qt5/include/QtGui/qpaintdevice.h \
		/usr/lib/qt5/include/QtCore/qrect.h \
		/usr/lib/qt5/include/QtCore/qsize.h \
		/usr/lib/qt5/include/QtGui/qpalette.h \
		/usr/lib/qt5/include/QtGui/qcolor.h \
		/usr/lib/qt5/include/QtGui/qrgb.h \
		/usr/lib/qt5/include/QtCore/qstringlist.h \
		/usr/lib/qt5/include/QtCore/qdatastream.h \
		/usr/lib/qt5/include/QtCore/qregexp.h \
		/usr/lib/qt5/include/QtCore/qstringmatcher.h \
		/usr/lib/qt5/include/QtGui/qbrush.h \
		/usr/lib/qt5/include/QtGui/qmatrix.h \
		/usr/lib/qt5/include/QtGui/qpolygon.h \
		/usr/lib/qt5/include/QtGui/qregion.h \
		/usr/lib/qt5/include/QtCore/qline.h \
		/usr/lib/qt5/include/QtGui/qtransform.h \
		/usr/lib/qt5/include/QtGui/qpainterpath.h \
		/usr/lib/qt5/include/QtGui/qimage.h \
		/usr/lib/qt5/include/QtGui/qpixmap.h \
		/usr/lib/qt5/include/QtCore/qsharedpointer.h \
		/usr/lib/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/lib/qt5/include/QtGui/qfont.h \
		/usr/lib/qt5/include/QtGui/qfontmetrics.h \
		/usr/lib/qt5/include/QtGui/qfontinfo.h \
		/usr/lib/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/lib/qt5/include/QtGui/qcursor.h \
		/usr/lib/qt5/include/QtGui/qkeysequence.h \
		/usr/lib/qt5/include/QtGui/qevent.h \
		/usr/lib/qt5/include/QtCore/qurl.h \
		/usr/lib/qt5/include/QtCore/qurlquery.h \
		/usr/lib/qt5/include/QtCore/qfile.h \
		/usr/lib/qt5/include/QtCore/qfiledevice.h \
		/usr/lib/qt5/include/QtGui/qvector2d.h \
		/usr/lib/qt5/include/QtGui/qtouchdevice.h \
		/usr/lib/qt5/include/QtGui/qvalidator.h \
		/usr/lib/qt5/include/QtGui/qicon.h \
		/usr/lib/qt5/include/QtWidgets/qslider.h \
		/usr/lib/qt5/include/QtWidgets/qabstractslider.h \
		/usr/lib/qt5/include/QtWidgets/qstyle.h \
		/usr/lib/qt5/include/QtWidgets/qtabbar.h \
		/usr/lib/qt5/include/QtWidgets/qtabwidget.h \
		/usr/lib/qt5/include/QtWidgets/qrubberband.h \
		/usr/lib/qt5/include/QtWidgets/qframe.h \
		/usr/lib/qt5/include/QtWidgets/QStyledItemDelegate \
		/usr/lib/qt5/include/QtWidgets/qstyleditemdelegate.h \
		/usr/lib/qt5/include/QtWidgets/qabstractitemdelegate.h \
		/usr/lib/qt5/include/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/CustomizableItemDelegate.o CustomizableItemDelegate.cpp

../../tmp/CustomizableSpinBox.o: CustomizableSpinBox.cpp CustomizableSpinBox.h \
		/usr/lib/qt5/include/QtCore/QString \
		/usr/lib/qt5/include/QtCore/qstring.h \
		/usr/lib/qt5/include/QtCore/qchar.h \
		/usr/lib/qt5/include/QtCore/qglobal.h \
		/usr/lib/qt5/include/QtCore/qconfig.h \
		/usr/lib/qt5/include/QtCore/qfeatures.h \
		/usr/lib/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib/qt5/include/QtCore/qlogging.h \
		/usr/lib/qt5/include/QtCore/qflags.h \
		/usr/lib/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib/qt5/include/QtCore/qtypetraits.h \
		/usr/lib/qt5/include/QtCore/qsysinfo.h \
		/usr/lib/qt5/include/QtCore/qbytearray.h \
		/usr/lib/qt5/include/QtCore/qrefcount.h \
		/usr/lib/qt5/include/QtCore/qatomic.h \
		/usr/lib/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib/qt5/include/QtCore/qatomic_power.h \
		/usr/lib/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib/qt5/include/QtCore/qnamespace.h \
		/usr/lib/qt5/include/QtCore/qarraydata.h \
		/usr/lib/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib/qt5/include/QtCore/QLocale \
		/usr/lib/qt5/include/QtCore/qlocale.h \
		/usr/lib/qt5/include/QtCore/qvariant.h \
		/usr/lib/qt5/include/QtCore/qlist.h \
		/usr/lib/qt5/include/QtCore/qalgorithms.h \
		/usr/lib/qt5/include/QtCore/qiterator.h \
		/usr/lib/qt5/include/QtCore/qmetatype.h \
		/usr/lib/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib/qt5/include/QtCore/qisenum.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib/qt5/include/QtCore/qmap.h \
		/usr/lib/qt5/include/QtCore/qpair.h \
		/usr/lib/qt5/include/QtCore/qdebug.h \
		/usr/lib/qt5/include/QtCore/qhash.h \
		/usr/lib/qt5/include/QtCore/qtextstream.h \
		/usr/lib/qt5/include/QtCore/qiodevice.h \
		/usr/lib/qt5/include/QtCore/qobject.h \
		/usr/lib/qt5/include/QtCore/qcoreevent.h \
		/usr/lib/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib/qt5/include/QtCore/qobject_impl.h \
		/usr/lib/qt5/include/QtCore/qvector.h \
		/usr/lib/qt5/include/QtCore/qpoint.h \
		/usr/lib/qt5/include/QtCore/qset.h \
		/usr/lib/qt5/include/QtCore/qcontiguouscache.h \
		/usr/lib/qt5/include/QtCore/qshareddata.h \
		/usr/lib/qt5/include/QtGui/QValidator \
		/usr/lib/qt5/include/QtGui/qvalidator.h \
		/usr/lib/qt5/include/QtCore/qregexp.h \
		/usr/lib/qt5/include/QtWidgets/QAbstractSpinBox \
		/usr/lib/qt5/include/QtWidgets/qabstractspinbox.h \
		/usr/lib/qt5/include/QtWidgets/qwidget.h \
		/usr/lib/qt5/include/QtGui/qwindowdefs.h \
		/usr/lib/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/lib/qt5/include/QtCore/qmargins.h \
		/usr/lib/qt5/include/QtGui/qpaintdevice.h \
		/usr/lib/qt5/include/QtCore/qrect.h \
		/usr/lib/qt5/include/QtCore/qsize.h \
		/usr/lib/qt5/include/QtGui/qpalette.h \
		/usr/lib/qt5/include/QtGui/qcolor.h \
		/usr/lib/qt5/include/QtGui/qrgb.h \
		/usr/lib/qt5/include/QtCore/qstringlist.h \
		/usr/lib/qt5/include/QtCore/qdatastream.h \
		/usr/lib/qt5/include/QtCore/qstringmatcher.h \
		/usr/lib/qt5/include/QtGui/qbrush.h \
		/usr/lib/qt5/include/QtGui/qmatrix.h \
		/usr/lib/qt5/include/QtGui/qpolygon.h \
		/usr/lib/qt5/include/QtGui/qregion.h \
		/usr/lib/qt5/include/QtCore/qline.h \
		/usr/lib/qt5/include/QtGui/qtransform.h \
		/usr/lib/qt5/include/QtGui/qpainterpath.h \
		/usr/lib/qt5/include/QtGui/qimage.h \
		/usr/lib/qt5/include/QtGui/qpixmap.h \
		/usr/lib/qt5/include/QtCore/qsharedpointer.h \
		/usr/lib/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/lib/qt5/include/QtGui/qfont.h \
		/usr/lib/qt5/include/QtGui/qfontmetrics.h \
		/usr/lib/qt5/include/QtGui/qfontinfo.h \
		/usr/lib/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/lib/qt5/include/QtGui/qcursor.h \
		/usr/lib/qt5/include/QtGui/qkeysequence.h \
		/usr/lib/qt5/include/QtGui/qevent.h \
		/usr/lib/qt5/include/QtCore/qurl.h \
		/usr/lib/qt5/include/QtCore/qurlquery.h \
		/usr/lib/qt5/include/QtCore/qfile.h \
		/usr/lib/qt5/include/QtCore/qfiledevice.h \
		/usr/lib/qt5/include/QtGui/qvector2d.h \
		/usr/lib/qt5/include/QtGui/qtouchdevice.h \
		/usr/lib/qt5/include/QtWidgets/QWidget \
		/usr/lib/qt5/include/QtWidgets/QLineEdit \
		/usr/lib/qt5/include/QtWidgets/qlineedit.h \
		/usr/lib/qt5/include/QtWidgets/qframe.h \
		/usr/lib/qt5/include/QtGui/qtextcursor.h \
		/usr/lib/qt5/include/QtGui/qtextformat.h \
		/usr/lib/qt5/include/QtGui/qpen.h \
		/usr/lib/qt5/include/QtGui/qtextoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/CustomizableSpinBox.o CustomizableSpinBox.cpp

../../tmp/CustomizableState.o: CustomizableState.cpp CustomizableState.h \
		/usr/lib/qt5/include/QtCore/QObject \
		/usr/lib/qt5/include/QtCore/qobject.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib/qt5/include/QtCore/qnamespace.h \
		/usr/lib/qt5/include/QtCore/qglobal.h \
		/usr/lib/qt5/include/QtCore/qconfig.h \
		/usr/lib/qt5/include/QtCore/qfeatures.h \
		/usr/lib/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib/qt5/include/QtCore/qlogging.h \
		/usr/lib/qt5/include/QtCore/qflags.h \
		/usr/lib/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib/qt5/include/QtCore/qtypetraits.h \
		/usr/lib/qt5/include/QtCore/qsysinfo.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib/qt5/include/QtCore/qstring.h \
		/usr/lib/qt5/include/QtCore/qchar.h \
		/usr/lib/qt5/include/QtCore/qbytearray.h \
		/usr/lib/qt5/include/QtCore/qrefcount.h \
		/usr/lib/qt5/include/QtCore/qatomic.h \
		/usr/lib/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib/qt5/include/QtCore/qatomic_power.h \
		/usr/lib/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib/qt5/include/QtCore/qarraydata.h \
		/usr/lib/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib/qt5/include/QtCore/qlist.h \
		/usr/lib/qt5/include/QtCore/qalgorithms.h \
		/usr/lib/qt5/include/QtCore/qiterator.h \
		/usr/lib/qt5/include/QtCore/qcoreevent.h \
		/usr/lib/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib/qt5/include/QtCore/qmetatype.h \
		/usr/lib/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib/qt5/include/QtCore/qisenum.h \
		/usr/lib/qt5/include/QtCore/qobject_impl.h \
		/usr/lib/qt5/include/QtCore/QState \
		/usr/lib/qt5/include/QtCore/qstate.h \
		/usr/lib/qt5/include/QtCore/qabstractstate.h \
		/usr/lib/qt5/include/QtCore/QEvent \
		/usr/lib/qt5/include/QtCore/QAbstractState \
		/usr/lib/qt5/include/QtCore/QVector \
		/usr/lib/qt5/include/QtCore/qvector.h \
		/usr/lib/qt5/include/QtCore/qpoint.h \
		/usr/lib/qt5/include/QtCore/QLatin1String \
		/usr/lib/qt5/include/QtCore/QVariant \
		/usr/lib/qt5/include/QtCore/qvariant.h \
		/usr/lib/qt5/include/QtCore/qmap.h \
		/usr/lib/qt5/include/QtCore/qpair.h \
		/usr/lib/qt5/include/QtCore/qdebug.h \
		/usr/lib/qt5/include/QtCore/qhash.h \
		/usr/lib/qt5/include/QtCore/qtextstream.h \
		/usr/lib/qt5/include/QtCore/qiodevice.h \
		/usr/lib/qt5/include/QtCore/qlocale.h \
		/usr/lib/qt5/include/QtCore/qshareddata.h \
		/usr/lib/qt5/include/QtCore/qset.h \
		/usr/lib/qt5/include/QtCore/qcontiguouscache.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/CustomizableState.o CustomizableState.cpp

../../tmp/LedIndicator.o: LedIndicator.cpp /usr/lib/qt5/include/QtCore/QEvent \
		/usr/lib/qt5/include/QtCore/qcoreevent.h \
		/usr/lib/qt5/include/QtCore/qnamespace.h \
		/usr/lib/qt5/include/QtCore/qglobal.h \
		/usr/lib/qt5/include/QtCore/qconfig.h \
		/usr/lib/qt5/include/QtCore/qfeatures.h \
		/usr/lib/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib/qt5/include/QtCore/qlogging.h \
		/usr/lib/qt5/include/QtCore/qflags.h \
		/usr/lib/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib/qt5/include/QtCore/qtypetraits.h \
		/usr/lib/qt5/include/QtCore/qsysinfo.h \
		/usr/lib/qt5/include/QtCore/qbytearray.h \
		/usr/lib/qt5/include/QtCore/qrefcount.h \
		/usr/lib/qt5/include/QtCore/qatomic.h \
		/usr/lib/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib/qt5/include/QtCore/qatomic_power.h \
		/usr/lib/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib/qt5/include/QtCore/qarraydata.h \
		/usr/lib/qt5/include/QtCore/qstring.h \
		/usr/lib/qt5/include/QtCore/qchar.h \
		/usr/lib/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib/qt5/include/QtCore/QRect \
		/usr/lib/qt5/include/QtCore/qrect.h \
		/usr/lib/qt5/include/QtCore/qsize.h \
		/usr/lib/qt5/include/QtCore/qpoint.h \
		/usr/lib/qt5/include/QtCore/QSize \
		/usr/lib/qt5/include/QtGui/QImage \
		/usr/lib/qt5/include/QtGui/qimage.h \
		/usr/lib/qt5/include/QtGui/qtransform.h \
		/usr/lib/qt5/include/QtGui/qmatrix.h \
		/usr/lib/qt5/include/QtGui/qpolygon.h \
		/usr/lib/qt5/include/QtCore/qvector.h \
		/usr/lib/qt5/include/QtCore/qalgorithms.h \
		/usr/lib/qt5/include/QtCore/qiterator.h \
		/usr/lib/qt5/include/QtCore/qlist.h \
		/usr/lib/qt5/include/QtGui/qregion.h \
		/usr/lib/qt5/include/QtGui/qwindowdefs.h \
		/usr/lib/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/lib/qt5/include/QtCore/qdatastream.h \
		/usr/lib/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib/qt5/include/QtCore/qiodevice.h \
		/usr/lib/qt5/include/QtCore/qobject.h \
		/usr/lib/qt5/include/QtCore/qmetatype.h \
		/usr/lib/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib/qt5/include/QtCore/qisenum.h \
		/usr/lib/qt5/include/QtCore/qobject_impl.h \
		/usr/lib/qt5/include/QtCore/qpair.h \
		/usr/lib/qt5/include/QtCore/qline.h \
		/usr/lib/qt5/include/QtGui/qpainterpath.h \
		/usr/lib/qt5/include/QtGui/qpaintdevice.h \
		/usr/lib/qt5/include/QtGui/qrgb.h \
		/usr/lib/qt5/include/QtCore/qstringlist.h \
		/usr/lib/qt5/include/QtCore/qregexp.h \
		/usr/lib/qt5/include/QtCore/qstringmatcher.h \
		/usr/lib/qt5/include/QtGui/QPaintEvent \
		/usr/lib/qt5/include/QtGui/qevent.h \
		/usr/lib/qt5/include/QtGui/qkeysequence.h \
		/usr/lib/qt5/include/QtCore/qvariant.h \
		/usr/lib/qt5/include/QtCore/qmap.h \
		/usr/lib/qt5/include/QtCore/qdebug.h \
		/usr/lib/qt5/include/QtCore/qhash.h \
		/usr/lib/qt5/include/QtCore/qtextstream.h \
		/usr/lib/qt5/include/QtCore/qlocale.h \
		/usr/lib/qt5/include/QtCore/qshareddata.h \
		/usr/lib/qt5/include/QtCore/qset.h \
		/usr/lib/qt5/include/QtCore/qcontiguouscache.h \
		/usr/lib/qt5/include/QtCore/qurl.h \
		/usr/lib/qt5/include/QtCore/qurlquery.h \
		/usr/lib/qt5/include/QtCore/qfile.h \
		/usr/lib/qt5/include/QtCore/qfiledevice.h \
		/usr/lib/qt5/include/QtGui/qvector2d.h \
		/usr/lib/qt5/include/QtGui/qtouchdevice.h \
		/usr/lib/qt5/include/QtGui/QPainter \
		/usr/lib/qt5/include/QtGui/qpainter.h \
		/usr/lib/qt5/include/QtGui/qpixmap.h \
		/usr/lib/qt5/include/QtGui/qcolor.h \
		/usr/lib/qt5/include/QtCore/qsharedpointer.h \
		/usr/lib/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/lib/qt5/include/QtGui/qtextoption.h \
		/usr/lib/qt5/include/QtGui/qpen.h \
		/usr/lib/qt5/include/QtGui/qbrush.h \
		/usr/lib/qt5/include/QtGui/qfontinfo.h \
		/usr/lib/qt5/include/QtGui/qfont.h \
		/usr/lib/qt5/include/QtGui/qfontmetrics.h \
		/usr/lib/qt5/include/QtWidgets/QAbstractButton \
		/usr/lib/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/lib/qt5/include/QtGui/qicon.h \
		/usr/lib/qt5/include/QtWidgets/qwidget.h \
		/usr/lib/qt5/include/QtCore/qmargins.h \
		/usr/lib/qt5/include/QtGui/qpalette.h \
		/usr/lib/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/lib/qt5/include/QtGui/qcursor.h \
		/usr/lib/qt5/include/QtWidgets/QWidget \
		LedIndicator.h \
		/usr/lib/qt5/include/QtGui/QColor
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/LedIndicator.o LedIndicator.cpp

../../tmp/ScopedPropertyRollback.o: ScopedPropertyRollback.cpp ScopedPropertyRollback.h \
		/usr/lib/qt5/include/QtCore/QObject \
		/usr/lib/qt5/include/QtCore/qobject.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib/qt5/include/QtCore/qnamespace.h \
		/usr/lib/qt5/include/QtCore/qglobal.h \
		/usr/lib/qt5/include/QtCore/qconfig.h \
		/usr/lib/qt5/include/QtCore/qfeatures.h \
		/usr/lib/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib/qt5/include/QtCore/qlogging.h \
		/usr/lib/qt5/include/QtCore/qflags.h \
		/usr/lib/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib/qt5/include/QtCore/qtypetraits.h \
		/usr/lib/qt5/include/QtCore/qsysinfo.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib/qt5/include/QtCore/qstring.h \
		/usr/lib/qt5/include/QtCore/qchar.h \
		/usr/lib/qt5/include/QtCore/qbytearray.h \
		/usr/lib/qt5/include/QtCore/qrefcount.h \
		/usr/lib/qt5/include/QtCore/qatomic.h \
		/usr/lib/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib/qt5/include/QtCore/qatomic_power.h \
		/usr/lib/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib/qt5/include/QtCore/qarraydata.h \
		/usr/lib/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib/qt5/include/QtCore/qlist.h \
		/usr/lib/qt5/include/QtCore/qalgorithms.h \
		/usr/lib/qt5/include/QtCore/qiterator.h \
		/usr/lib/qt5/include/QtCore/qcoreevent.h \
		/usr/lib/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib/qt5/include/QtCore/qmetatype.h \
		/usr/lib/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib/qt5/include/QtCore/qisenum.h \
		/usr/lib/qt5/include/QtCore/qobject_impl.h \
		/usr/lib/qt5/include/QtCore/QVariant \
		/usr/lib/qt5/include/QtCore/qvariant.h \
		/usr/lib/qt5/include/QtCore/qmap.h \
		/usr/lib/qt5/include/QtCore/qpair.h \
		/usr/lib/qt5/include/QtCore/qdebug.h \
		/usr/lib/qt5/include/QtCore/qhash.h \
		/usr/lib/qt5/include/QtCore/qtextstream.h \
		/usr/lib/qt5/include/QtCore/qiodevice.h \
		/usr/lib/qt5/include/QtCore/qlocale.h \
		/usr/lib/qt5/include/QtCore/qshareddata.h \
		/usr/lib/qt5/include/QtCore/qvector.h \
		/usr/lib/qt5/include/QtCore/qpoint.h \
		/usr/lib/qt5/include/QtCore/qset.h \
		/usr/lib/qt5/include/QtCore/qcontiguouscache.h \
		/usr/lib/qt5/include/QtCore/QByteArray
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/ScopedPropertyRollback.o ScopedPropertyRollback.cpp

../../tmp/Validator.o: Validator.cpp Validator.h \
		/usr/lib/qt5/include/QtCore/QObject \
		/usr/lib/qt5/include/QtCore/qobject.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib/qt5/include/QtCore/qnamespace.h \
		/usr/lib/qt5/include/QtCore/qglobal.h \
		/usr/lib/qt5/include/QtCore/qconfig.h \
		/usr/lib/qt5/include/QtCore/qfeatures.h \
		/usr/lib/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib/qt5/include/QtCore/qlogging.h \
		/usr/lib/qt5/include/QtCore/qflags.h \
		/usr/lib/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib/qt5/include/QtCore/qtypetraits.h \
		/usr/lib/qt5/include/QtCore/qsysinfo.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib/qt5/include/QtCore/qstring.h \
		/usr/lib/qt5/include/QtCore/qchar.h \
		/usr/lib/qt5/include/QtCore/qbytearray.h \
		/usr/lib/qt5/include/QtCore/qrefcount.h \
		/usr/lib/qt5/include/QtCore/qatomic.h \
		/usr/lib/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib/qt5/include/QtCore/qatomic_power.h \
		/usr/lib/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib/qt5/include/QtCore/qarraydata.h \
		/usr/lib/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib/qt5/include/QtCore/qlist.h \
		/usr/lib/qt5/include/QtCore/qalgorithms.h \
		/usr/lib/qt5/include/QtCore/qiterator.h \
		/usr/lib/qt5/include/QtCore/qcoreevent.h \
		/usr/lib/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib/qt5/include/QtCore/qmetatype.h \
		/usr/lib/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib/qt5/include/QtCore/qisenum.h \
		/usr/lib/qt5/include/QtCore/qobject_impl.h \
		/usr/lib/qt5/include/QtCore/QList \
		/usr/lib/qt5/include/QtCore/QString \
		/usr/lib/qt5/include/QtGui/QValidator \
		/usr/lib/qt5/include/QtGui/qvalidator.h \
		/usr/lib/qt5/include/QtCore/qregexp.h \
		/usr/lib/qt5/include/QtCore/qlocale.h \
		/usr/lib/qt5/include/QtCore/qvariant.h \
		/usr/lib/qt5/include/QtCore/qmap.h \
		/usr/lib/qt5/include/QtCore/qpair.h \
		/usr/lib/qt5/include/QtCore/qdebug.h \
		/usr/lib/qt5/include/QtCore/qhash.h \
		/usr/lib/qt5/include/QtCore/qtextstream.h \
		/usr/lib/qt5/include/QtCore/qiodevice.h \
		/usr/lib/qt5/include/QtCore/qvector.h \
		/usr/lib/qt5/include/QtCore/qpoint.h \
		/usr/lib/qt5/include/QtCore/qset.h \
		/usr/lib/qt5/include/QtCore/qcontiguouscache.h \
		/usr/lib/qt5/include/QtCore/qshareddata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/Validator.o Validator.cpp

../../tmp/Waiter.o: Waiter.cpp /usr/lib/qt5/include/QtCore/QDebug \
		/usr/lib/qt5/include/QtCore/qdebug.h \
		/usr/lib/qt5/include/QtCore/qalgorithms.h \
		/usr/lib/qt5/include/QtCore/qglobal.h \
		/usr/lib/qt5/include/QtCore/qconfig.h \
		/usr/lib/qt5/include/QtCore/qfeatures.h \
		/usr/lib/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib/qt5/include/QtCore/qlogging.h \
		/usr/lib/qt5/include/QtCore/qflags.h \
		/usr/lib/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib/qt5/include/QtCore/qtypetraits.h \
		/usr/lib/qt5/include/QtCore/qsysinfo.h \
		/usr/lib/qt5/include/QtCore/qhash.h \
		/usr/lib/qt5/include/QtCore/qchar.h \
		/usr/lib/qt5/include/QtCore/qiterator.h \
		/usr/lib/qt5/include/QtCore/qlist.h \
		/usr/lib/qt5/include/QtCore/qrefcount.h \
		/usr/lib/qt5/include/QtCore/qatomic.h \
		/usr/lib/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib/qt5/include/QtCore/qatomic_power.h \
		/usr/lib/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib/qt5/include/QtCore/qpair.h \
		/usr/lib/qt5/include/QtCore/qmap.h \
		/usr/lib/qt5/include/QtCore/qtextstream.h \
		/usr/lib/qt5/include/QtCore/qiodevice.h \
		/usr/lib/qt5/include/QtCore/qobject.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib/qt5/include/QtCore/qnamespace.h \
		/usr/lib/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib/qt5/include/QtCore/qstring.h \
		/usr/lib/qt5/include/QtCore/qbytearray.h \
		/usr/lib/qt5/include/QtCore/qarraydata.h \
		/usr/lib/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib/qt5/include/QtCore/qcoreevent.h \
		/usr/lib/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib/qt5/include/QtCore/qmetatype.h \
		/usr/lib/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib/qt5/include/QtCore/qisenum.h \
		/usr/lib/qt5/include/QtCore/qobject_impl.h \
		/usr/lib/qt5/include/QtCore/qlocale.h \
		/usr/lib/qt5/include/QtCore/qvariant.h \
		/usr/lib/qt5/include/QtCore/qshareddata.h \
		/usr/lib/qt5/include/QtCore/qvector.h \
		/usr/lib/qt5/include/QtCore/qpoint.h \
		/usr/lib/qt5/include/QtCore/qset.h \
		/usr/lib/qt5/include/QtCore/qcontiguouscache.h \
		/usr/lib/qt5/include/QtCore/QElapsedTimer \
		/usr/lib/qt5/include/QtCore/qelapsedtimer.h \
		/usr/lib/qt5/include/QtCore/QCoreApplication \
		/usr/lib/qt5/include/QtCore/qcoreapplication.h \
		/usr/lib/qt5/include/QtCore/qeventloop.h \
		/usr/lib/qt5/include/QtCore/QObject \
		ConnectionHolder.h \
		/usr/lib/qt5/include/QtCore/QVector \
		/usr/lib/qt5/include/QtCore/QMetaObject \
		Waiter.h \
		/usr/lib/qt5/include/QtCore/QList \
		/usr/lib/qt5/include/QtCore/QVariant
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/Waiter.o Waiter.cpp

../../tmp/qrc_GardenOfEdenCreationKit.o: ../../tmp/qrc_GardenOfEdenCreationKit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/qrc_GardenOfEdenCreationKit.o ../../tmp/qrc_GardenOfEdenCreationKit.cpp

../../tmp/moc_CustomizableState.o: ../../tmp/moc_CustomizableState.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/moc_CustomizableState.o ../../tmp/moc_CustomizableState.cpp

../../tmp/moc_Waiter.o: ../../tmp/moc_Waiter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../../tmp/moc_Waiter.o ../../tmp/moc_Waiter.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

